export const ACTION_LOGIN = "ACTION_LOGIN"
export const ACTION_LOGOUT = "ACTION_LOGOUT"
export const ACTION_PROFILE_MENU_OPEN = "ACTION_PROFILE_MENU_OPEN"
export const ACTION_PROFILE_MENU_CLOSE = "ACTION_PROFILE_MENU_CLOSE"